## Eddie Martin
## Data Wrangling Final Project
## 12/17/2024

In [2]:
## Websites Used https://www.nfl.com/standings/league/2023/REG and https://www.spotrac.com/nfl/cap/_/year/2023/sort/cap_maximum_space
### The NFL.com website tracks the each teams record as well as some statistics such as points scored and allowed.
### The spotrac.com website tracks the financials for each team such as payroll.

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [67]:
# This block of code scrapes the data from Spotrac.com and adds it to a data frame
driver = webdriver.Chrome()

all_teams = []
all_cap_space = []
all_years = []
def spotrac_data(year):
    url = f"https://www.spotrac.com/nfl/cap/_/year/{year}/sort/cap_maximum_space"
    driver.get(url)

    team = []
    cap_space = []

    for i in range(1,33):
        team_name_xpath = f'//*[@id="table-wrapper"]/div[2]/div[2]/table/tbody/tr[{i}]/td[2]'
        cap_amount_xpath = f'//*[@id="table-wrapper"]/div[2]/div[2]/table/tbody/tr[{i}]/td[7]'

        team_name = driver.find_element(By.XPATH, team_name_xpath).text
        cap_amount = driver.find_element(By.XPATH, cap_amount_xpath).text

        team.append(team_name)
        cap_space.append(cap_amount)

    return team, cap_space

for year in range(2023, 2010, -1):
    print(f"Scraping data for year {year}...")
    teams, cap_space = spotrac_data(year)
    all_teams.extend(teams)
    all_cap_space.extend(cap_space)
    all_years.extend([year] * len(teams))

data = {
    'Year': all_years,
    'Team Abbr': all_teams,
    'Cap Space': all_cap_space
}

cap_df = pd.DataFrame(data)

print(cap_df)
cap_df.to_csv('Spotrac_Raw_Data.csv', index = False)
driver.quit()

Scraping data for year 2023...
Scraping data for year 2022...
Scraping data for year 2021...
Scraping data for year 2020...
Scraping data for year 2019...
Scraping data for year 2018...
Scraping data for year 2017...
Scraping data for year 2016...
Scraping data for year 2015...
Scraping data for year 2014...
Scraping data for year 2013...
Scraping data for year 2012...
Scraping data for year 2011...
     Year Team Abbr    Cap Space
0    2023        SF  $37,989,804
1    2023       CLE  $29,876,309
2    2023       WAS  $12,093,648
3    2023        LV  $11,529,499
4    2023       ARI  $11,175,765
..    ...       ...          ...
411  2011        SD  $-1,371,575
412  2011       DET  $-2,654,126
413  2011       PIT  $-3,439,023
414  2011       MIA  $-3,542,373
415  2011       ATL  $-5,639,378

[416 rows x 3 columns]

In [69]:
#This block of code scrapes data from the NFL and puts it into a data frame
driver = webdriver.Chrome()

all_teams = []
all_wins = []
all_losses = []
all_ties = []
all_win_pcts = []
all_years = []

def nfl_data(year):
    url = f"https://www.nfl.com/standings/league/{year}/REG"
    driver.get(url)

    teams = []
    wins = []
    losses = []
    ties = []
    win_pct = []

    for i in range(1,33):
        team_name_xpath = f'//*[@id="main-content"]/section[3]/div/div/div/div/div[2]/table/tbody/tr[{i}]/td[1]'
        team_wins_xpath = f'//*[@id="main-content"]/section[3]/div/div/div/div/div[2]/table/tbody/tr[{i}]/td[2]'
        team_losses_xpath = f'//*[@id="main-content"]/section[3]/div/div/div/div/div[2]/table/tbody/tr[{i}]/td[3]'
        team_ties_xpath = f'//*[@id="main-content"]/section[3]/div/div/div/div/div[2]/table/tbody/tr[{i}]/td[4]'
        team_pct_xpath = f'//*[@id="main-content"]/section[3]/div/div/div/div/div[2]/table/tbody/tr[{i}]/td[5]'

        team_name = driver.find_element(By.XPATH, team_name_xpath).text
        team_wins = driver.find_element(By.XPATH, team_wins_xpath).text
        team_losses = driver.find_element(By.XPATH, team_losses_xpath).text
        team_ties = driver.find_element(By.XPATH, team_ties_xpath).text
        team_win_pct = driver.find_element(By.XPATH, team_pct_xpath).text

        team_name = team_name.replace("\nx\nz", "").replace("\nx", "").replace("\n*", "").replace("\ny","")
        
        teams.append(team_name)
        wins.append(team_wins)
        losses.append(team_losses)
        ties.append(team_ties)
        win_pct.append(team_win_pct)

    return teams, wins, losses, ties, win_pct

for year in range(2023,2010,-1):
    print(f"Scraping data for year {year}...")
    teams, wins, losses, ties, win_pct = nfl_data(year)
    all_teams.extend(teams)
    all_wins.extend(wins)
    all_losses.extend(losses)
    all_ties.extend(ties)
    all_win_pcts.extend(win_pct)
    all_years.extend([year] * len(teams))

data = {
    'Year': all_years,
    'Team': all_teams,
    'Wins': all_wins,
    'Losses': all_losses,
    'Ties': all_ties,
    'PCT': all_win_pcts
}

nfl_df = pd.DataFrame(data)

print(nfl_df)
nfl_df.to_csv('NFL_Raw_Data.csv', index = False)
driver.quit

Scraping data for year 2023...
Scraping data for year 2022...
Scraping data for year 2021...
Scraping data for year 2020...
Scraping data for year 2019...
Scraping data for year 2018...
Scraping data for year 2017...
Scraping data for year 2016...
Scraping data for year 2015...
Scraping data for year 2014...
Scraping data for year 2013...
Scraping data for year 2012...
Scraping data for year 2011...
     Year        Team Wins Losses Ties    PCT
0    2023      Ravens   13      4    0  0.765
1    2023     Cowboys   12      5    0  0.706
2    2023       Lions   12      5    0  0.706
3    2023       49ers   12      5    0  0.706
4    2023       Bills   11      6    0  0.647
..    ...         ...  ...    ...  ...    ...
411  2011      Browns    4     12    0  0.250
412  2011  Buccaneers    4     12    0  0.250
413  2011     Vikings    3     13    0  0.188
414  2011       Colts    2     14    0  0.125
415  2011        Rams    2     14    0  0.125

[416 rows x 6 columns]

In [6]:
# This gives the team names that have changed over this time period a common name
nfl_df['Team'] = nfl_df['Team'].replace({
    'Redskins': 'Commanders',
    'Football Team': 'Commanders',
    'Niners': '49ers'
})

print(nfl_df)

     Year        Team Wins Losses Ties    PCT
0    2023      Ravens   13      4    0  0.765
1    2023     Cowboys   12      5    0  0.706
2    2023       Lions   12      5    0  0.706
3    2023       49ers   12      5    0  0.706
4    2023       Bills   11      6    0  0.647
..    ...         ...  ...    ...  ...    ...
411  2011      Browns    4     12    0  0.250
412  2011  Buccaneers    4     12    0  0.250
413  2011     Vikings    3     13    0  0.188
414  2011       Colts    2     14    0  0.125
415  2011        Rams    2     14    0  0.125

[416 rows x 6 columns]

In [7]:
# This maps the abbreviations from the Spotrac df to the team names of the NFL df
team_mapping = {
    'ARI': 'Cardinals',
    'ATL': 'Falcons',
    'BAL': 'Ravens',
    'BUF': 'Bills',
    'CAR': 'Panthers',
    'CHI': 'Bears',
    'CIN': 'Bengals',
    'CLE': 'Browns',
    'DAL': 'Cowboys',
    'DEN': 'Broncos',
    'DET': 'Lions',
    'GB': 'Packers',
    'HOU': 'Texans',
    'IND': 'Colts',
    'JAX': 'Jaguars',
    'KC': 'Chiefs',
    'LAC': 'Chargers',
    'LAR': 'Rams',
    'LV': 'Raiders',
    'MIA': 'Dolphins',
    'MIN': 'Vikings',
    'NE': 'Patriots',
    'NO': 'Saints',
    'NYG': 'Giants',
    'NYJ': 'Jets',
    'PHI': 'Eagles',
    'PIT': 'Steelers',
    'SEA': 'Seahawks',
    'SF': '49ers',
    'TB': 'Buccaneers',
    'TEN': 'Titans',
    'WAS': 'Commanders',
    'OAK': 'Raiders',
    'SD': 'Chargers',
    'STL': 'Rams',
}

cap_df ['Team'] = cap_df['Team Abbr'].replace(team_mapping)

In [8]:
# This combines both data frames into one
merged_df = pd.merge(nfl_df, cap_df, on = ['Team' , 'Year'], how = 'left')
merged_df = merged_df.drop(columns = ['Team Abbr'])
merged_df
merged_df.to_csv('NFL_Cap_Data_Raw.csv', index = False)

     Year        Team Wins Losses Ties    PCT    Cap Space
0    2023      Ravens   13      4    0  0.765     $882,714
1    2023     Cowboys   12      5    0  0.706  $10,801,968
2    2023       Lions   12      5    0  0.706   $3,800,950
3    2023       49ers   12      5    0  0.706  $37,989,804
4    2023       Bills   11      6    0  0.647    $-792,453
..    ...         ...  ...    ...  ...    ...          ...
411  2011      Browns    4     12    0  0.250  $25,515,480
412  2011  Buccaneers    4     12    0  0.250  $56,160,701
413  2011     Vikings    3     13    0  0.188     $671,877
414  2011       Colts    2     14    0  0.125   $4,590,862
415  2011        Rams    2     14    0  0.125  $18,115,323

[416 rows x 7 columns]